export type RoleId = 'R-REG' | 'R-SCR' | 'R-DOC' | 'R-LAB' | 'R-PHA' | 'R-FIN' | 'R-ADMIN';
export type Locale = 'th' | 'en';
export type LocalText = Record<Locale, string>;
export type Workspace = { id: RoleId; name: LocalText; title: LocalText; module: string; milestone: string; columns: LocalText[]; action: LocalText; scope: LocalText; clinicalHeader: boolean };
const tx = (th: string, en: string): LocalText => ({ th, en });
export const workspaces: Workspace[] = [
  { id: 'R-REG', name: tx('เวชระเบียน', 'Registration'), title: tx('ทะเบียนผู้ป่วย', 'Patient registry'), module: 'PAT-01', milestone: 'M1', columns: [tx('HN', 'HN'), tx('ชื่อ–สกุล', 'Patient name'), tx('วันเกิด', 'Date of birth'), tx('สถานะ', 'Status')], action: tx('ลงทะเบียนผู้ป่วย', 'Register patient'), scope: tx('ข้อมูลระบุตัวตนและการเปิดรับบริการ', 'Patient identity and service registration'), clinicalHeader: false },
  { id: 'R-SCR', name: tx('พยาบาลคัดกรอง', 'Screening nurse'), title: tx('คิวคัดกรอง', 'Triage worklist'), module: 'PAT-02', milestone: 'M2', columns: [tx('VN / HN', 'VN / HN'), tx('ชื่อ–สกุล', 'Patient name'), tx('เข้ารับบริการ', 'Arrival'), tx('สถานะคัดกรอง', 'Triage status')], action: tx('บันทึกสัญญาณชีพ', 'Record vital signs'), scope: tx('คัดกรองและบันทึกสัญญาณชีพ', 'Triage and vital observations'), clinicalHeader: true },
  { id: 'R-DOC', name: tx('แพทย์', 'Doctor'), title: tx('ห้องตรวจผู้ป่วยนอก', 'OPD consulting room'), module: 'CLI-01 / CLI-02', milestone: 'M3', columns: [tx('VN / HN', 'VN / HN'), tx('ชื่อ–สกุล', 'Patient name'), tx('รับบริการ', 'Service'), tx('สถานะ', 'Status')], action: tx('เปิดเวชระเบียน', 'Open clinical record'), scope: tx('เวชระเบียนและคำสั่งการรักษา', 'Clinical record and orders'), clinicalHeader: true },
  { id: 'R-LAB', name: tx('ห้องปฏิบัติการ', 'Laboratory'), title: tx('รายการตรวจทางห้องปฏิบัติการ', 'Laboratory worklist'), module: 'ANC-01', milestone: 'M4', columns: [tx('เลขคำสั่ง', 'Order number'), tx('HN', 'HN'), tx('รายการตรวจ', 'Test'), tx('สิ่งส่งตรวจ / สถานะ', 'Specimen / status')], action: tx('บันทึกผลตรวจ', 'Enter result'), scope: tx('สิ่งส่งตรวจและผลตรวจในหน่วยงานที่รับผิดชอบ', 'Assigned laboratory section and results'), clinicalHeader: true },
  { id: 'R-PHA', name: tx('เภสัชกรรม', 'Pharmacy'), title: tx('รายการรอจ่ายยา', 'Dispensing worklist'), module: 'PHM-02', milestone: 'M4', columns: [tx('เลขคำสั่ง', 'Order number'), tx('HN', 'HN'), tx('รายการยา', 'Medication'), tx('สถานะ', 'Status')], action: tx('ตรวจสอบและจ่ายยา', 'Review and dispense'), scope: tx('ตรวจสอบคำสั่งยาและบันทึกการจ่าย', 'Medication orders and dispensing'), clinicalHeader: true },
  { id: 'R-FIN', name: tx('การเงิน', 'Finance'), title: tx('รายการค่าใช้จ่าย', 'Encounter charges'), module: 'FIN-01', milestone: 'M4', columns: [tx('เลขบัญชี', 'Account number'), tx('HN', 'HN'), tx('ยอดเงิน (บาท)', 'Amount (THB)'), tx('สถานะ', 'Status')], action: tx('ดูค่าใช้จ่าย', 'View charges'), scope: tx('ข้อมูลสำหรับออกบิลตามสิทธิ์การเงิน', 'Billing information within finance permissions'), clinicalHeader: false },
  { id: 'R-ADMIN', name: tx('ผู้ดูแลระบบ', 'Administration'), title: tx('การตั้งค่าระบบสาธิต', 'Demo configuration'), module: 'PLT-01', milestone: 'M5', columns: [tx('รายการ', 'Setting'), tx('ขอบเขต', 'Scope'), tx('สถานะ', 'Status')], action: tx('แก้ไขการตั้งค่า', 'Edit configuration'), scope: tx('ข้อมูลหลักและบัญชีสาธิต', 'Master data and demo identities'), clinicalHeader: false },
];
export function getWorkspace(value: string): Workspace | undefined { return workspaces.find((w) => w.id === value); }
export const copy = {
  th: { role: 'สำรวจหน้าจอตามบทบาท', banner: 'ระบบสาธิต · M0 Foundation', bannerDetail: 'ยังไม่รองรับการลงทะเบียนหรือบันทึกข้อมูลผู้ป่วย', workspace: 'พื้นที่ปฏิบัติงาน', overview: 'สถานะโครงระบบ', patient: 'ยังไม่ได้เลือกผู้ป่วย', patientHint: 'ข้อมูลผู้ป่วยจะแสดงเมื่อเปิดรับบริการในระยะถัดไป', noRecords: 'ยังไม่มีรายการในหน้าจอนี้', emptyHint: 'ขณะนี้เปิดดูโครงหน้าจอได้ ฟังก์ชันบันทึกข้อมูลจะเพิ่มตามแผนพัฒนา', planned: 'วางแผนไว้', identity: 'การเลือกบทบาทนี้เป็นหน้าจอตัวอย่าง ยังไม่ได้เข้าสู่ระบบ', runtime: 'การเชื่อมต่อในเครื่อง', refresh: 'ตรวจอีกครั้ง', checking: 'กำลังตรวจสอบ', ready: 'เชื่อมต่อแล้ว', unavailable: 'ยังไม่พร้อม', notChecked: 'ยังไม่ได้ตรวจ', backend: 'บริการและฐานข้อมูล', local: 'ข้อมูลสังเคราะห์เท่านั้น', skip: 'ข้ามไปเนื้อหาหลัก', next: 'ขั้นตอนที่จะเพิ่ม', journey: 'เส้นทางผู้ป่วยนอก', emptyStatus: 'รอเชื่อมข้อมูล', guide: 'เริ่มต้นพัฒนาต่อ', guideDetail: 'เปิด HANDOFF_TO_CODEX.md แล้วเริ่มงาน M1-01', runtimeHint: 'ผลนี้ตรวจการเชื่อมต่อและรุ่นฐานข้อมูล ไม่ใช่สถานะพร้อมใช้งานทางคลินิก' },
  en: { role: 'Explore by role', banner: 'Demo · M0 Foundation', bannerDetail: 'Patient registration and clinical data entry are not available yet', workspace: 'Workspace', overview: 'Foundation status', patient: 'No patient selected', patientHint: 'Patient context will appear when a service encounter is opened', noRecords: 'No records in this workspace yet', emptyHint: 'This release previews the workspace. Data entry follows the milestone plan.', planned: 'Planned', identity: 'Role selection is a navigation preview. You are not signed in.', runtime: 'Connection status', refresh: 'Check again', checking: 'Checking', ready: 'Connected', unavailable: 'Not ready', notChecked: 'Not checked', backend: 'Service and database', local: 'Synthetic data only', skip: 'Skip to main content', next: 'Upcoming workflow', journey: 'Outpatient journey', emptyStatus: 'Awaiting data connection', guide: 'Continue development', guideDetail: 'Open HANDOFF_TO_CODEX.md and start task M1-01', runtimeHint: 'This checks connectivity and schema version, not clinical readiness.' },
} as const;
